### Display configuration - this is specific to current Arcology setup
# `man 5 sway-output` for more information about this section.

# Left screen
output DP-3 mode 1920x1080@60Hz position 0,0

# Right screen
output DP-2 mode 1920x1080@144Hz position 1920,0

