### Keyboard and other input devices config
# `man 5 sway-input` for more information about this section.


# I live in Norway, I guess I've doxed myself, rip. :C
input type:keyboard {
    xkb_layout "no"
}

